Enumerable ruby project
iam-Akshat/Enumerables-Ruby pull request #1
Opened 2020-11-20 08:40 UTC by rayking12

**Tasks Done:**
Created a repository
Created a _gitflow_ 
created a **development branch** as _default_
created a feature branch
added a **ruby** file
added **ruby linters**
worked on the project details and specifics
added readme file
corrected linter errors

2020-11-20 09:40 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: 

HELLO @iam-Akshat  AND @rayking12  :wave:  VERY NICE PROGRESS. THIS IS ACTUALLY VERY IMPRESSIVE FOR A FIRST REVIEW.

However, there a few issues that need to be fixed kindly check below :arrow_down: 

- [ ] There are some rubocop errors in your project. Kindly fix all the errors.

![Screenshot from 2020-11-20 11-44-58](https://user-images.githubusercontent.com/32361963/99784901-83d18080-2b2d-11eb-9250-c0c4b07a06bc.png)


### if you have any question kindly reach me on slack @peterrobert

### HAPPY CODING :computer:

2020-11-20 09:40 UTC, peterrobert commented on my_enumerables.rb
> +  end
If no block is given, then my_each should return an enumerator. Kindly check the link below :arrow_down: 
[each](https://ruby-doc.org/core-2.6.4/Array.html#method-i-eachl)

Example:

`e = [1,2,3].each` should return `# => #<Enumerator: [1, 2, 3]:each> ` 

in your method, it is actually returning an error. You can read more on how to solve this problem [here](https://blog.arkency.com/2014/01/ruby-to-enum-for-enumerator/)

2020-11-20 09:40 UTC, peterrobert commented on my_enumerables.rb
> +  end
Just like with my_each above, this method should also return an enumerator when no block is given.

Example

`e = [1,2,3].each_with_index ` should return `# => #<Enumerator: [1, 2, 3]:each_with_index>`.

NB: Kindly use the link above to learn more about how to solve this issue.

2020-11-20 09:40 UTC, peterrobert commented on my_enumerables.rb
> +  end
Just like with my_each above, this method should also return an enumerator when no block is given.

Example

`e = [1,2,3].select` should return # => #`<Enumerator: [1, 2, 3]:select>`.

NB: Kindly use the link above to learn more about how to solve this issue.

2020-11-20 09:40 UTC, peterrobert commented on my_enumerables.rb
> +  end
Kindly fix the following issues: 

- [ ] When you pass a regex to this method it should return false if any of the collection does not match the regex.

EXAMPLE:
`%w[ant bear cat].all?(/t/)                        #=> false` .  since the string **bear** doesnt have letter **t** then it means it returns false just like you can see.

Read more on it [here](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F) You can also use this [link](https://www.rubyguides.com/2015/06/ruby-regex/) too

Kindly test all the expectations when a regex is passed to this method

2020-11-20 09:40 UTC, peterrobert commented on my_enumerables.rb
> +  end
Just like my_all above, You should implement the behavior of the method when the regex is passed to it. For this method, it behaves differently. see below :arrow_down: 

When a regex is passed to this method, it should return true if **any** of the collection matches the regex.

EXAMPLE:  `%w[ant bear cat].any?(/d/)                        #=> false`. As you can see since none of the strings contain letter **d** then the method returns false.

Kindly use the links provided above to learn more on this issue. KIndly fix it :smile:

2020-11-20 09:40 UTC, peterrobert commented on my_enumerables.rb
> +  end
Kindly fix the following two issues:

- [ ] When no block is given, or argument, then it should return true if none of the collection members is true.

EXAMPLE: `[nil, false].none?                                 #=> true` Kindly use this link to learn more about this issue.
[link](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F)

2020-11-20 09:40 UTC, peterrobert commented on my_enumerables.rb
> +end
In this method, It should raise a ** "LocalJumpError" ** when no block is given.

Kindly use this [link](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject) To read on it more

2020-11-20 13:30 UTC, mimipeshy commented
### STATUS : CHANGES REQUIRED :recycle: 

Hello team :wave:  :wave: , you guys have outdone yourselves in this project, you should be proud of yourselves. You have worked on almost all required except for a few things:

- [ ] Fix the rubocop error in your code. Hint: you are missing an end in the #my_each method, just above self.

- [ ]  enumerables #my_each returns an Enumerator if no block is given

- [ ]  enumerables #my_each_with_index returns an enumerator if no block is given

- [ ] enumerables #my_select returns an enumerator if no block is given

- [ ] enumerables #my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
 - If the collection passed to this method it matches the whole Regex, it should return true 
EXAMPLE:
`%w[ant bear cat].all? { |word| word.length >= 3 } => true` . since the length of all strings is greater than 4 it returns true just like you can see.

Read more on it here You can also use this [link](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F) too

- If the collection does not match the Regex, it should return a false
`%w[ant bear cat].all? { |word| word.length >= 4 } #=> false` since not all the lengths of a string are greater than 4 it returns a false

- [ ] enumerables #my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
-  If the collection passed to this method does not match any of the Regex, it should return false
Example
`%w[ant bear cat].any?(/d/)  #=> false`
-  If the collection passed to this method it matches any of the Regex, it should return true
Example
`%w[ant bear cat].any? { |word| word.length >= 4 } #=> true`

- [ ] ) enumerables #my_none? when no block or argument is given returns true only if none of the collection members is true
- If **none** of the collection members are true it should return a true
Example:
`%w{ant bear cat}.none?(/d/) #=> true` since none of the collection members contain letter d, it returns a true

- if **one** of the collection members is true, it should return a false
Example
`%w{ant bear cat}.none? { |word| word.length >= 4 } #=> false` since bear is more that 4 words, it returns a false

Thats all :relaxed:  , kindly fix the above and submit another review when done

Regards
Peris Ndanu
Feel free to slack me if you need any help.

2020-11-20 14:41 UTC, arslanbisharat reviewed
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

**Please have a look at the suggestions to get more understanding.**

- [ ] You submitted new PR for this project. Don't do this next time. Stick to the same PR. 

- [ ] You have previously described errors. Please work on that. 


**Please make the changes and request re-review for the given project**
Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-11-20 14:50 UTC, iam-Akshat commented
> arslanbisharat

I already made the changes in the other branch and submitted it for review.
Now am I suppose to reopen this branch?

2020-11-20 16:49 UTC, ElijahTobs requested changes
# Status: Changes Required :recycle: 

## Hi @iam-Akshat and @rayking12 

Good job implementing the change as requested by the previous TSE :+1: 
However, there are still some changes to be made before this project can be approved.

## [REQUIRED]

- [x] `my_all` and `my_any` fails when tested against a pattern other than Regex or a Class
- [x] `my_map` fails when tested against a range
- [x] `my_inject` fails when tested against a block without an initial value
- [x] `my_inject` fails when tested against a symbol without an initial value
- [ ] `multiply_els` is supposed to accept an array as an argument and multiply all the elements of the array together but it's not doing so

## [NICE TO HAVE]

- [ ] Add a live demo link of your custom enumerable methods to your README file. You can use [repl](https://repl.it)

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2020-11-23 08:59 UTC, Temmarie requested changes
### Changes Required! :recycle:
Hi @iam-Akshat and @rayking12  ! 👋 👋 
### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

**Variables used in testing:**

```
 ARRAY_SIZE = 100
  LOWEST_VALUE = 0
  HIGHEST_VALUE = 9

  array = Array.new(ARRAY_SIZE = rand(LOWEST_VALUE...HIGHEST_VALUE) } 
  block = proc { |num| num < (LOWEST_VALUE + HIGHEST_VALUE) / 2 } 
  words = %w[dog door rod blade] 
  range = Range.new(5, 50) 
  hash = { a: 1, b: 2, c: 3, d: 4, e: 5 } 
  numbers = [1, 2i, 3.14] 
  array_clone = array.clone
``` 

### Recommended Changes

**my_all**
- [ ] when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern.

```
expect(array.my_all?(3)).to be array.all?(3)
     
       expected false
            got true
```

- [ ]  #my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

`expect(array.my_map(my_proc) { |num| num < 10 }).to eq array.map(&my_proc)`

- [ ] #my_inject when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block.

```
expect(array.my_inject(&operation)).to eq array.inject(&operation)
 
expected: 414
            got: 422

```
- [ ]  #my_inject when a block is given without an initail value combines all elements of enum by applying a binary operation, specified by a block::range

```
  Failure/Error: actual = range.my_inject { |prod, n| prod * n }
     
     NoMethodError:
       undefined method `[]' for 5..50:Range
```
- [ ] #multiply_els accepts an array as an argument and multiplies all the elements of the array together using #my_inject

```
Failure/Error: expect(actual).to eq 40
     
       expected: 40
            got: 80

```







__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2020-11-23 14:29 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] should have a working `my_map`. See inline comment.

- [ ] should have a working `my_inject`. See inline comment.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-11-23 14:29 UTC, jubaan commented on my_enumerables.rb
> +  end
- [ ] `my_inject` is not working as the original `inject` method, also is not passing all test cases.

### `inject`` is an Enumerable that has these characteristics:
- Returns a `LocalJumpError` when no block is given and no symbol is passed as an argument.
```
[1, 2, 3].inject
# LocalJumpError (no block given)
```

- it does not modify/change the original array/range/hash.

**- it can accept an initial value and/or a symbol as an argument.**
```
[1, 2, 3].inject(2, :*)
# => 12

[1,2,3].inject(:+)
# => 6
```
**- When an initial value is not given combines all elements of enum**
```
[1,2,3].inject { |acc, e| acc += e }
# => 6
```

[Enumerable#inject](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-inject)

2020-11-23 17:20 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] Should have a working `my_inject` method. See inline comment.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-11-23 17:20 UTC, jubaan commented on my_enumerables.rb
> +  end
- [ ] The `my_inject` method is not returning the correct value.
```ruby
[1,2,3].my_inject { |acc, e| acc += e } # => 7 
[1,2,3].inject { |acc, e| acc += e } # => 6 

(1..3).my_inject { |acc, e| acc += e } # => 7 
(1..3).inject { |acc, e| acc += e } # => 6 
```

2020-11-24 08:43 UTC, Temmarie approved these changes
## Status: Approved :heavy_check_mark:

### Hi @iam-Akshat and @rayking12 ! 👋 👋 👋 

### You've come a long way from where you were and have learned a lot along the way. Thank you for making all of the required changes, and congratulations your project is approved!! :clap: :clap: :clap: :tada: 💯 💯 

### You may merge, good luck with your next projects! :rocket:
### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

2020-11-24 09:40 UTC, merged